CREATE ROLE MCADMINROLE PASSWORD 'MCADMINROLE';
CREATE ROLE MCUSERROLE PASSWORD 'MCUSERROLE';

CREATE USER MCADMINUSER WITH LOGIN PASSWORD 'MCADMINUSER';
CREATE USER MCUSER WITH LOGIN PASSWORD 'MCUSER';

GRANT MCADMINROLE TO MCADMINUSER;
GRANT MCUSERROLE TO MCUSER;

CREATE DATABASE MILLCHECKDB WITH OWNER = MCADMINROLE;
GRANT CONNECT, CREATE ON DATABASE MILLCHECKDB TO MCADMINROLE;
REVOKE ALL ON DATABASE MILLCHECKDB FROM PUBLIC;
REVOKE ALL ON DATABASE MILLCHECKDB FROM POSTGRES;
