CREATE ROLE MCADMINROLE WITH LOGIN PASSWORD 'MCADMINROLE';
CREATE ROLE MCUSERROLE WITH LOGIN PASSWORD 'MCUSERROLE';

CREATE USER MILLCHECKADMIN WITH LOGIN PASSWORD 'MILLCHECKADMIN';
CREATE USER MILLCHECKUSER WITH LOGIN PASSWORD 'MILLCHECKUSER';

GRANT MCADMINROLE TO MILLCHECKADMIN;
GRANT MCUSERROLE TO MILLCHECKUSER;

CREATE DATABASE MILLCHECKDB;
GRANT CREATE ON DATABASE MILLCHECKDB TO MCADMINROLE;
