/*
 CHECKBOX_DETAILS_T
- CHECKBOX_NBR int, unique, not null, primary key
- INIT_DATE timestamp with time zone, not null, default now()
- LAST_UPDATED_BY uuid, not null, (UUIDv7)
- LAST_REQUEST_ID uuid, not null, (UUIDv7)
- LAST_UPDATED_DATE timestamp with time zone, not null
- INDEXES
  - PK: CHECKBOX_NBR
  - IX1: LAST_UPDATED_BY
 */

CREATE TABLE CHECKBOX_DETAILS_T (
    CHECKBOX_NBR INT UNIQUE NOT NULL PRIMARY KEY,
    INIT_DATE TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    LAST_UPDATED_BY UUID NOT NULL,
    LAST_REQUEST_ID UUID NOT NULL,
    LAST_UPDATED_DATE TIMESTAMP WITH TIME ZONE NOT NULL
)
;

CREATE INDEX CHECKBOX_DETAILS_IX1 ON CHECKBOX_DETAILS_T (
    LAST_UPDATED_BY
)
;
