/*
 UPDATE_T
- UPDATE_DATE timestamp with time zone, not null, default now(), primary key
- CHECKBOX_NBR int, not null
- CHECKED boolean, not null
- UPDATED_BY uuid, not null, (UUIDv7)
- REQUEST_ID uuid, not null, (UUIDv7)
- SUCCESS boolean, not null
- INDEXES
  - PK: UPDATE_DATE
  - IX1: CHECKBOX_NBR
  - IX2: UPDATED_BY

 */

CREATE TABLE UPDATE_T (
    UPDATE_DATE TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW() PRIMARY KEY,
    CHECKBOX_NBR INT NOT NULL,
    CHECKED BOOLEAN NOT NULL,
    UPDATED_BY UUID NOT NULL,
    REQUEST_ID UUID NOT NULL,
    SUCCESS BOOLEAN NOT NULL
)
;

CREATE INDEX UPDATE_IX1 ON UPDATE_T ( CHECKBOX_NBR )
;
CREATE INDEX UPDATE_IX2 ON UPDATE_T ( UPDATED_BY )
;
